version: "3.8"

services:
  registry:
    image: registry:2
    ports:
      - "5000:5000"
    environment:
      REGISTRY_HTTP_ADDR: 0.0.0.0:5000
      REGISTRY_HTTP_TLS_CERTIFICATE: /certs/domain.crt
      REGISTRY_HTTP_TLS_KEY: /certs/domain.key
      REGISTRY_AUTH: htpasswd
      REGISTRY_AUTH_HTPASSWD_REALM: "Registry Realm"
      REGISTRY_AUTH_HTPASSWD_PATH: /auth/htpasswd
    volumes:
      - registry_data:/var/lib/registry
      - registry_auth:/auth
      - registry_certs:/certs
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager
    networks:
      - docker-net

volumes:
  registry_data:
    driver: local
    driver_opts:
      type: "nfs"
      o: "addr=nfsdocker,nolock,soft,rw"
      device: ":/srv/docker-volumes/nfs/registry/data"
  registry_auth:
    driver: local
    driver_opts:
      type: "nfs"
      o: "addr=nfsdocker,nolock,soft,rw"
      device: ":/srv/docker-volumes/nfs/registry/auth"
  registry_certs:
    driver: local
    driver_opts:
      type: "nfs"
      o: "addr=nfsdocker,nolock,soft,rw"
      device: ":/srv/docker-volumes/nfs/registry/certs"

networks:
  docker-net:
    driver: overlay
