version: "3.8"

services:

  mariadb:
    image: registry.local:5000/mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: supersecret
      MYSQL_DATABASE: app_db
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - docker-net
    deploy:
      placement:
        constraints:
          - node.role == worker
      restart_policy:
        condition: on-failure

  app:
    image: registry.local:5000/my-php-app:latest
    depends_on:
      - mariadb
    networks:
      - docker-net
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure
      update_config:
        parallelism: 1
        delay: 10s

  nginx:
    image: registry.local:5000/nginx:custom
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - app
    networks:
      - docker-net
    deploy:
      restart_policy:
        condition: on-failure

  vscode:
    image: registry.local:5000/codercom/code-server:latest
    environment:
      PASSWORD: "superpassword"
    ports:
      - "8443:8443"
    volumes:
      - vscode_data:/home/coder/project
    networks:
      - docker-net
    deploy:
      restart_policy:
        condition: on-failure

volumes:
  db_data:
    driver: local
    driver_opts:
      type: "nfs"
      o: "addr=registry.local,nolock,soft,rw"
      device: ":/srv/nfs/db"
  vscode_data:
    driver: local
    driver_opts:
      type: "nfs"
      o: "addr=registry.local,nolock,soft,rw"
      device: ":/srv/nfs/vscode"

networks:
  docker-net:
    driver: overlay
