version: "3.8"

services:
  nginx:
    build: .
    container_name: nginx-reverse-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./certs:/etc/nginx/certs:ro
    networks:
      - nginx-net
    restart: unless-stopped
